### ISSUE TITLE
Library unable to convert a lat/long point to an MGRS value

### ISSUE THREAD

**Issue by nateand** [ngageoint/mgrs-java#1]
This happens with a variety of points that are geographically close to each other. 

For example, occurs with  lat = 50.920338 and long = 128.4525.

#### Version Information:

  * MGRS Java Version: 2.1.0
  * MGRS Java Source: Maven
  * IDE Name & Version: Intellij 2022.2.2
  * Maven Version: 4.0.0
  * Java Version: 11.0.15
  * Platform & OS: Several, Linux and MacOS
  * Other Relevant Libraries:
Included library via pom.xml file: 

```
<dependency>
            <groupId>mil.nga</groupId>
            <artifactId>mgrs</artifactId>
            <version>2.1.0</version>
</dependency>
```

#### Expected Results:
When attempting to get an MGRS value from a lat/lon point:
`Point lat_lon_point = new Point(50.920338, 128.4525);`
`MGRS m = MGRS.from(lat_lon_point);`

#### Observed Results:

Happens on many platforms every time. 

#### Output:

 Result:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -18
at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
at java.base/java.lang.String.charAt(String.java:693)
at mil.nga.mgrs.MGRS.getRowLetter(MGRS.java:790)
at mil.nga.mgrs.MGRS.getRowLetter(MGRS.java:774)
```

#### Steps to Reproduce:

  1. Step One
  2. Step Two
  3. ...

#### Relevant Code:

```java
Point lat_lon_point = new Point(50.920338, 128.4525);
MGRS m = MGRS.from(lat_lon_point);
```

#### Test Files:

  * Links to any files needed for testing?

#### Additional Information:

  * Any additional configuration, data, or information that might help with the issue?

**Comment by bosborn** [comment]
[Point](https://github.com/ngageoint/grid-java/blob/master/src/main/java/mil/nga/grid/features/Point.java#L33) takes the longitude first.

```
Point lat_lon_point = new Point(128.4525, 50.920338);
MGRS m = MGRS.from(lat_lon_point);
System.out.println(m);
```

`52UDB6151641108`

**Comment by nateand** [comment]
Oh wow, I'm so sorry. Apologies for wasting your time and thank you for so quickly handling that!

**Comment by bosborn** [comment]
[Added latitude bounding and longitude normalization](https://github.com/ngageoint/mgrs-java/commit/0921e99c0d59a41b7eeed82a408ebf04547455a6) for the next version.  Produces a coordinate (possibly unexpected if the longitude and latitude are swapped) instead of an error.
